spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  redis:
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: 10000ms
    host: 127.0.0.1
app:

server:
  port: 8080
jwt:
  guest:
    effective-time: 300
  secret: helloworld
  user:
    effective-time: 10800
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
logging:
  path: /data/log/
#  level:
#    root:

c3p0:
  driverClass: com.mysql.jdbc.Driver
  maxStatements: 1000
  breakAfterAcquireFailure: false
  maxIdleTime: 1800000
  acquireRetryAttempts: 30
  password: 123456
  testConnectionOnCheckout: true
  minPoolSize: 2
  acquireIncrement: 3
  jdbcUrl: jdbc:mysql://localhost:3306/literature?useSSL=true&serverTimezone=UTC&autoReconnection=true
  acquireRetryDelay: 1000
  idleConnectionTestPeriod: 60
  preferredTestQuery: select 1
  initialPoolSize: 3
  user: root
  maxPoolSize: 30